name: Tools Lint

on:
  pull_request:
    paths:
      - 'tools/cmd/**'
      - 'tools/internal/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.1
        with:
          go-version-file: tools/go.mod

      - name: Run golangci-lint
        run: |
          make -C tools lint GOCMD=$(which go)
